# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Anime In Life' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Anime In Life

  pod ‘Firebase’
  pod ‘Firebase/Database’
  pod 'Firebase/Storage'

end
